ALTER PROCEDURE Cre_InsPreCliEnc
@IdCliente int output,
@Foto image,
@IdTipoPersona varchar(15),
@Nombre varchar(50),
@SegundoNombre varchar(25),
@ApellidoPaterno varchar(25),
@ApellidoMaterno varchar(25),
@IdSexo int,
@Edad int,
@FechaNacimiento date,
@IdEstadoNacimiento int,
@IdMunicipioNacimiento int,
@IdNacionalidad int,
@Telefono varchar(15),
@Correo varchar(50),
@RFC varchar(15),
@CURP varchar(25),
@IdEstatus int,
@IdEstadoCivil int,
@ImporteSolicitado float,
@ImporteLetra varchar(200),
@IdTipoCambio int,
@ActividadHabitual varchar(200),
@Calle varchar(25),
@Colonia varchar(50),
@Numero int,
@IdEstado int,
@IdMunicipio int,
@Poblacion varchar(50),
@CodigoPostal int,
@IdConyugue int,
@FechaMatrimonio date,
@IdEstadoMatrimonio int,
@IdMunicipioMatrimonio int,
@Fecha datetime
AS
BEGIN
 SET NOCOUNT ON
    MERGE dbo.Cre_Preregistro_Cliente_Encabezado as TARGET
    USING(SELECT @IdCliente,@Foto,@IdTipoPersona,@Nombre,@SegundoNombre,@ApellidoPaterno,@ApellidoMaterno,@IdSexo,@Edad,@FechaNacimiento,
	@IdEstadoNacimiento,@IDMunicipioNacimiento,@IdNacionalidad,@Telefono,@Correo,@RFC,@CURP,@IdEstatus,@IdEstadoCivil,@ImporteSolicitado,@ImporteLetra,
	@IdTipoCambio,@ActividadHabitual,@Calle,@Colonia,@Numero,@IdEstado,@IdMunicipio,@Poblacion,@CodigoPostal,@IdConyugue,@fechaMatrimonio,@IdEstadoMatrimonio,@IdMunicipioMatrimonio,@Fecha) 
	AS SOURCE(IdCliente,Foto,IdTipoPersona,Nombre,SegundoNombre,ApellidoPaterno,ApellidoMaterno,IdSexo,Edad,FechaNacimiento,
	IdEstadoNacimiento,IDMunicipioNacimiento,IdNacionalidad,Telefono,Correo,RFC,CURP,IdEstatus,IdEstadoCivil,ImporteSolicitado,ImporteLetra,
	IdTipoCambio,ActividadHabitual,Calle,Colonia,Numero,IdEstado,IdMunicipio,Poblacion,CodigoPostal,IdConyugue,FechaMatrimonio,IdEstadoMatrimonio,IdMunicipioMatrimonio,Fecha)
    ON (TARGET.IdCliente = SOURCE.IdCliente)
WHEN MATCHED THEN
UPDATE SET 
Foto = source.Foto,
IdTipoPersona = source.IdTipoPersona,
Nombre = source.Nombre,
SegundoNombre = source.SegundoNombre,
ApellidoPaterno = source.ApellidoPaterno,
ApellidoMaterno = source.ApellidoMaterno,
IdSexo = source.IdSexo,
Edad = source.Edad,
FechaNacimiento = source.FechaNacimiento,
IdEstadoNacimiento = source.IdEstadoNacimiento,
IdMunicipioNacimiento = source.IdMunicipioNacimiento,
IdNacionalidad = source.IdNacionalidad,
Telefono = source.Telefono,
Correo = source.Correo,
RFC = source.RFC,
CURP = source.CURP,
IdEstatus = source.IdEstatus,
IdEstadoCivil = source.IdEstadoCivil,
ImporteSolicitado = source.ImporteSolicitado,
ImporteLetra = source.ImporteLetra,
IdTipoCambio = source.IdTIpoCambio,
ActividadHabitual = source.ActividadHabitual,
Calle = source.Calle,
Colonia = source.Colonia,
Numero = source.Numero,
IdEstado = source.IdEstado,
IdMunicipio = source.IdMunicipio,
Poblacion = source.Poblacion,
CodigoPostal = source.CodigoPostal,
IdConyugue = source.IdConyugue,
FechaMatrimonio = source.FechaMatrimonio,
IdEstadoMatrimonio = source.IdEstadoMatrimonio,
IdMunicipioMatrimonio = source.IdMunicipioMatrimonio,
Fecha = source.Fecha
WHEN NOT MATCHED THEN
        INSERT (
Foto,
IdTipoPersona,
Nombre,
SegundoNombre,
ApellidoPaterno,
ApellidoMaterno,
IdSexo,
Edad,
FechaNacimiento,
IdEstadoNacimiento,
IdMunicipioNacimiento,
IdNacionalidad,
Telefono,
Correo,
RFC,
CURP,
IdEstatus,
IdEstadoCivil,
ImporteSolicitado,
ImporteLetra,
IdTipoCambio,
ActividadHabitual,
Calle,
Colonia,
Numero,
IdEstado,
IdMunicipio,
Poblacion,
CodigoPostal,
IdConyugue,
FechaMatrimonio,
IdEstadoMatrimonio,
IdMunicipioMatrimonio,
Fecha)
        VALUES (
source.Foto,
source.IdTipoPersona,
source.Nombre,
source.SegundoNombre,
source.ApellidoPaterno,
source.ApellidoMaterno,
source.IdSexo,
source.Edad,
source.FechaNacimiento,
source.IdEstadoNacimiento,
source.IdMunicipioNacimiento,
source.IdNacionalidad,
source.Telefono,
source.Correo,
source.RFC,
source.CURP,
source.IdEstatus,
source.IdEstadoCivil,
source.ImporteSolicitado,
source.ImporteLetra,
source.IdTipoCambio,
source.ActividadHabitual,
source.Calle,
source.Colonia,
source.Numero,
source.IdEstado,
source.IdMunicipio,
source.Poblacion,
source.CodigoPostal,
source.IdConyugue,
source.FechaMatrimonio,
source.IdEstadoMatrimonio,
source.IdMunicipioMatrimonio,
source.Fecha);
		SET @IdCliente = SCOPE_IDENTITY()				
END
RETURN @IdCliente		