create table Cre_Preregistro_Cliente_Encabezado(
IdCliente int primary key identity(1,1) not null,
Foto image,
IdTipoPersona varchar(15),
Nombre varchar(25),
SegundoNombre varchar(25),
ApellidoPaterno varchar(25),
ApellidoMaterno varchar(25),
IdSexo int,
Edad int,
FechaNacimiento date,
IdEstadoNacimiento int,
IdMunicipioNacimiento int,
IdNacionalidad int,
Telefono varchar(15),
Correo varchar(50),
RFC varchar(15),
CURP varchar(25),
IdEstatus int,
IdEstadoCivil int,
ImporteSolicitado float,
ImporteLetra varchar(200),
IdTipoCambio int,
ActividadHabitual varchar(200),
Calle varchar (25),
Colonia varchar(50),
Numero int,
IdEstado int,
IdMunicipio int,
Poblacion varchar(50),
CodigoPostal int,
IdConyugue int,
FechaMatrimonio date,
IdEstadoMatrimonio int,
IdMunicipioMatrimonio int,
Fecha datetime
)
